logging:
  file:
    path: ./logs
  level:
    com:
      cloud:
        user: debug
    root: info
server:
  port: 18080
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      config:
        enabled: true
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: public
        refresh-enabled: true
        server-addr: http://localhost:8848
      discovery:
        namespace: public
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: cloud_user_route
          uri: lb://cloud-user
          predicates:
            - Path=/cloud-user/**
          filters:
            - StripPrefix=1

        - id: cloud_admin_route
          uri: lb://cloud-admin
          predicates:
            - Path=/cloud-admin/**
          filters:
            - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
